# Generated by Django 3.2 on 2022-07-03 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_post_created_on'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-created_on']},
        ),
    ]
